"""Generate reports/macros.tex from reports/data/phase_quantities.json.

Every number in reports/advisor_update_phases_1-6.tex is a \\newcommand
macro defined here, not a hardcoded literal in the prose — rerun this
after any phase_quantities.json update instead of hand-editing macros.tex.
"""

import json
import re
from pathlib import Path

DATA_PATH = Path(__file__).parent / "data" / "phase_quantities.json"
OUT_PATH = Path(__file__).parent / "macros.tex"


_DIGIT_WORDS = {
    "0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
}


def _spell_digits(word: str) -> str:
    """LaTeX macro names must be pure letters -- spell out any digits
    (e.g. "iter4" -> "IterFour", "mt5" -> "MtFive") instead of stripping them,
    so distinct keys that only differ by a digit don't collide."""
    out = []
    for ch in word:
        out.append(_DIGIT_WORDS[ch] if ch.isdigit() else ch)
    return "".join(out)


def to_camel(phase: str, key: str) -> str:
    """phase1 + ha_spearman -> PhaseOneHaSpearman (LaTeX macro names can't contain digits/underscores).

    Digits are spelled out, not stripped (e.g. "iter0" -> "IterZero"), so
    keys that only differ by a digit (iter0 vs iter1) don't collide."""
    phase_word = "Phase" + _DIGIT_WORDS.get(phase[-1], phase[-1])
    parts = re.split(r"[_\s]+", key)
    camel_parts = []
    for p in parts:
        spelled = _spell_digits(p)
        camel_parts.append(spelled[0].upper() + spelled[1:] if spelled else spelled)
    return phase_word + "".join(camel_parts)


def main():
    data = json.loads(DATA_PATH.read_text())
    lines = [
        "% AUTO-GENERATED by reports/generate_macros.py from reports/data/phase_quantities.json",
        "% Do not hand-edit -- update the JSON and regenerate.",
        "",
    ]
    for phase, values in data.items():
        if phase.startswith("_"):
            continue
        lines.append(f"% --- {phase} ---")
        for key, value in values.items():
            macro = to_camel(phase, key)
            lines.append(f"\\newcommand{{\\{macro}}}{{{value}}}")
        lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
