"""Prompt templates, replicated as closely as possible from the visible text
of Wu, Aycock & Monz (2025) "Please Translate Again", Appendix B (Figures
9-12 for the decompose/draft/refine/proofread chain; Figure 13 for the
single-pass baseline).

Note on fidelity: the decomposition prompt (Figure 9 in the PDF) is cut off
after the "Idiomatic Expressions" category — the paper's Section 2 mentions
the categories cover "meanings, topics, idiomatic expressions etc." but the
figure only renders the idiomatic-expressions bullet in full. We replicate
exactly what's visible rather than inventing the missing categories.
"""

SYSTEM_PROMPT = "You are a helpful assistant."

DECOMPOSITION_TEMPLATE = """You will be asked to translate a piece of text from {src_lang} into {tgt_lang} following stages of the translation process. Here is the context in which the text appears:

Context: {source_text}

To start, let's do some pre-drafting research on the above context.

Research: During this phase, thorough research is essential to address components of the context text that pose translation challenges. The goal is to establish a comprehensive translation plan that covers the following categories:

Idiomatic Expressions:
- Identify idiomatic expressions that cannot be directly translated word-for-word into {tgt_lang}."""

# L1_cot_tool only: same decomposition prompt, plus a mechanically-appended
# retrieved resource and an explicit instruction to decide whether/how to use it.
DECOMPOSITION_WITH_TOOL_SUFFIX = """

You are also given a retrieved translation memory match, which may or may not be relevant or reliable for this translation. Decide whether and how to use it as part of your translation plan.

Retrieved TM match:
Source: {tm_source}
Translation: {tm_reference}"""

DRAFT_TEMPLATE = """Now, let's move on to the drafting stage.

Draft Translation:
In this phase, your primary objective is to create a draft translation that accurately conveys the meaning of the source text presented below. At this stage, it is crucial to focus on adequacy, ensuring that your translation closely adheres to the source text. Your response should conclude with the draft translation. If context is missing, generate a general translation that is adaptable to various contexts. Avoid adding any additional information not present in the source text. All elements of the source text should be present in the translation.
Provide your single best translation of the following text, guided by the pre-drafting analysis, without adding anything further:

{src_lang}: {source_text}"""

REFINEMENT_TEMPLATE = """Now let's move to the next stage.

Post-editing with local refinement: In this stage, the primary aim is to refine the draft translation by making micro-level improvements that improve the draft's fluency.

Provide only one refined translation and do not output anything else after that."""

PROOFREADING_TEMPLATE = """You are tasked with proofreading a translation that has been revised for improved fluency. The refined translation has been generated by editing the draft translation.

Proofreading and Final Editing: The goal is to provide a polished final translation of the source text. For your reference, below are the source text, the draft, and refined translations.

Source Text: {source_text}
Draft Translation: {draft}
Refined Translation: {refined}

Please proofread the refined text for grammar, spelling, punctuation, terminology, and overall fluency. Ensure the translation accurately reflects the original meaning and style. Provide only the final, polished translation on the first line."""

# L1_baseline: single-pass, mirrors the paper's "translate again" Step 1
# prompt (Figure 13) minus the word "again" (this IS the first pass).
BASELINE_TEMPLATE = """Please translate the following text from {src_lang} to {tgt_lang}. Provide only one translation and do not output anything else after that.

{src_lang}: {source_text}"""

# L1_tool: mechanically prepend the retrieved resource — no reasoning
# instruction, just inject and translate.
TOOL_TEMPLATE = """Reference translation memory match (may or may not be relevant):
Source: {tm_source}
Translation: {tm_reference}

Please translate the following text from {src_lang} to {tgt_lang}, using the reference match above if it is helpful. Provide only one translation and do not output anything else after that.

{src_lang}: {source_text}"""
